
binary_sensor:
  - platform: gpio
    pin:
      number: 32
      mode:
        input: true
        pullup: true
    name: "Left Button"
    filters:
      - delayed_on: 10ms
    on_click:
      - min_length: 20ms
        max_length: 500ms
        then:
          - display.page.show_previous: screen
          - component.update: screen
      - min_length: 5s
        max_length: 10s
        then:
          - ${co2_action}: co2sensor
  - platform: gpio
    pin:
      number: 33
      mode:
        input: true
        pullup: true
    name: "Right Button"
    filters:
      - delayed_on: 10ms
    on_click:
      - min_length: 20ms
        max_length: 500ms
        then:
          - display.page.show_next: screen
          - component.update: screen
      - min_length: 5s
        max_length: 10s
        then:
          - lambda: |-
              esp_restart();
